hsl_transit_dbt:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: hsl-transit
      dataset: dbt_analytics
      keyfile: ../secrets/gcp-key.json
      location: EU
      threads: 4
      priority: interactive